### ISSUE TITLE
 build constraints exclude all Go files in upiterrider/ffi@v0.1.0-beta.9 on darwin

### ISSUE THREAD

**Issue by Xuanwo** [JupiterRider/ffi#4]
Hi, @JupiterRider. A user reported that `github.com/jupiterrider/ffi` failed to build on Darwin. I believe this library should be able to build on Darwin as well. Perhaps we should allow these files to build on Darwin?

For more context: https://github.com/apache/opendal/discussions/4996

---

I'm willing to help get this fixed. And maybe add some test in CI to cover.

**Comment by JupiterRider** [comment]
Hey @Xuanwo , I added macOS with 51655c1a7824d0d9cdbb4f9a533bca26b5f9e25 .
You can try it by running `go get github.com/jupiterrider/ffi@51655c1a7824d0d9cdbb4f9a533bca26b5f9e25`.

**Comment by Xuanwo** [comment]
Thanks for the prompt fix. 

I don't have the device to help verify it. But I think I can contribute an integration test to avoid regression. What do you think?

**Comment by JupiterRider** [comment]
@Xuanwo After a little trail and error, I finally have a working CI workflow: 9dafd5739f9fcb6cdac3d37c13c00a9c3de243ad

If you have any improvement suggestions, let me know or feel free to open a pull request.

**Comment by Xuanwo** [comment]
> @Xuanwo After a little trail and error, I finally have a working CI workflow: 9dafd5739f9fcb6cdac3d37c13c00a9c3de243ad
> 
> 
> 
> If you have any improvement suggestions, let me know or feel free to open a pull request.

Hi, would you like to submit your changes as a PR to make it easier for us to collaborate?

**Comment by JupiterRider** [comment]
Of course. I created a pull request: #5

**Comment by JupiterRider** [comment]
macOS support is now live with [v0.1.0](https://github.com/JupiterRider/ffi/releases/tag/v0.1.0) 🚀
