### ISSUE TITLE
Why not use cgo to compile libffi? This way, it can be independent of the environment. 

### ISSUE THREAD

**Issue by fanybook** [JupiterRider/ffi#6]
Why not use cgo to compile libffi? This way, it can be independent of the environment.

**Comment by JupiterRider** [comment]
Hey @fanybook,
this repository was initially created to extend the functionally of purego. Purego is a project which allows you to call functions inside shared libraries without cgo. That means there is no need of having a c-compiler or cross compiler toolchain when building for other platforms.

If I understand your question correctly, you want to statically link libffi, so you don't need any extra .dll/.so/.dlylib on the target system?

This is what the libffi readme says:
> Some programs may not know at the time of compilation what arguments are to be passed to a function. For instance, an interpreter may be told at run-time about the number and types of arguments used to call a given function. Libffi can be used in such programs to provide a bridge from the interpreter program to compiled code.
> 
> The libffi library provides a portable, high level programming interface to various calling conventions. This allows a programmer to call any function specified by a call interface description at run time.

Do you even have any need for libffi, if you use cgo?

Cheers!
